version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: sympy
    versions:
    - 1.7.1
